### ISSUE TITLE
Version 18.2 of the VTM doesn't support API version 3.8

### ISSUE THREAD

**Issue by cholmes1111** [beyondcomputing-org/NewRelic.Brocade.VTM#1]
If no api version is specified in the plugin.json configuation file, the api version will default to version 3.8. As of version 18.2 of the VTM, version 3.8 of the API is unavailable.

The plugin should be updated in two ways.

1. The default api version should be updated to at least 4.0. It would be preferable to update it to 6.0 as that's the most current version of the API in version 18.2 of the VTM
2. The casting of the APIVersion variable should be changed to a decimal. In more recent versions of the VTM, new versions of the API always have .0 (5.0,6.0). As a double data type, C# strips the .0 off resulting in an incorrect URL

**Incorrect URL example**
/api/tm/6/status/local_tm/statistics/globals

**Correct URL example**
/api/tm/6.0/status/local_tm/statistics/globals

**Comment by eelkram** [comment]
The plugin has been updated to support 6.0.  The default has also been updated to 6.0 as the current default was very very old and shouldn't be used in a production scenario anymore.
